server:
  port: 7001

#Eureka配置
eureka:
  instance:
    hostname: localhost #Eureka服务端的实例名称
  client:
    registerWithEureka: false # 表示是否向eureka注册中心注册自己
    fetchRegistry: false #fetch-registry如果为false，则表示自己为注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机
     # 集群（关联）：
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/